backend:
  name: git-gateway
  branch: main

# Remove local_backend for now
media_folder: "images" 
public_folder: "/images"

collections:
  - name: "test"
    label: "Test"
    files:
      - label: "Test Page"
        name: "test"
        file: "test.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}