backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Main Headline", name: "headline", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}